---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarantool-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tarantool-operator
  template:
    metadata:
      labels:
        name: tarantool-operator
    spec:
      serviceAccountName: tarantool-operator
      imagePullSecrets:
        - name: ecr
      containers:
        - name: tarantool-operator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - tarantool-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: tarantool-operator
              value: "tarantool-operator"
---
